name: python hello world
on: [push]
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run python script
              run: python3 src/main.py